<?php

namespace Location\PlaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{   
    public function getNearestCities($lat, $lng)
    {   
        $radius = 0.15;
        $qb = $this->createQueryBuilder('c')
            ->where('c.lat BETWEEN :lat-'.$radius.' AND :lat+'.$radius)
            ->andWhere('c.lng BETWEEN :lng-'.$radius.' AND :lng+'.$radius)
            ->andWhere('c.lng <> :lng')
            ->andWhere('c.lat <> :lat')
            ->setParameter('lat', $lat)
            ->setParameter('lng', $lng)
            ->orderBy('c.name', 'ASC')
            ->getQuery();

        return $qb->getResult();

    }
}
